export const movies = [
  "The Silent Horizon",
  "Echoes of Tomorrow",
  "Midnight Mirage",
  "The Glass Empire",
  "Beneath Crimson Skies",
  "Neon Shadows",
  "Fragments of Eternity",
  "The Forgotten Signal",
  "Lunar Tide",
  "The Last Outpost",
  "Starlight Rebellion",
  "Ghosts of the Machine",
  "Velvet Storm",
  "The Iron Veil",
  "Hollow Crown",
  "After the Ashes",
  "A Thousand Suns",
  "Digital Prophecy",
  "Whispering Walls",
  "The Darkest Hourglass",
  "Eternal Drift",
  "The Final Accord",
  "Wraith Protocol",
  "Shadows Over Eden",
  "The Clockwork Horizon"
];
